server:
  port: 9080

spring:
  application:
    name: user-service # 微服务名称
  profiles:
    active: dev

  # nacos
  cloud:
    nacos:
      server-addr: 192.168.219.101:8848 # nacos地址

  # rabbitmq
  rabbitmq:
    host: 192.168.219.101 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /szml # 虚拟主机
    username: szml # 用户名
    password: 123456 # 密码

    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息

#  # 数据库
#  datasource:
#    url: jdbc:mysql://192.168.237.101:4406/szml?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
  # Redis

  redis:
    database: 3
    host: 192.168.219.101
    port: 6379
    password: 123456
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms

  # shardingsphere
  shardingsphere:
    mode:
      type: Memory
    props:
      sql-show: true

    datasource:
      names: ds0,ds1

      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.219.101:4407/ds0?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.219.101:4408/ds1?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456

    # 规则配置
    rules:
      sharding:
        # 单表配置（不分片）
        #标准分片表配置（数据节点配置）
        tables:
          users:
            actual-data-nodes: ds$->{0..1}.users0

            #分片算法配置（库）
            database-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: alg_database

        # 分片算法属性配置
        sharding-algorithms:
          alg_database:
            type: INLINE
            props:
              algorithm-expression: ds$->{user_id % 2}


# 设置日志级别为DEBUG（开发环境）
logging:
  level:
    com:
      jins:
        mapper: debug
        service: info
        controller: info

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto