server:
  port: 9080
spring:
  application:
    name: user-service # 微服务名称
  profiles:
    active: dev
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/szml?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  # Redis
  redis:
    database: 3
    host: 192.168.237.101
    port: 6379
    password: 123456
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms

# 设置日志级别为DEBUG（开发环境）
logging:
  level:
    com:
      jins:
        mapper: debug
        service: info
        controller: info

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto